### ISSUE TITLE
Changes to common footer

### ISSUE THREAD

**Issue by gvwilson** [swctasks/assets#13]
1.  Use a three-column layout for the footer.
2.  Put the icons for GitHub, Twitter, and YouTube in the middle column.
3. Stack them vertically to save space (?).
4. Use this in all footers.
5. Get rid of the titles "About This Site" and "Services".
6. Add a link to 'License' to the right-hand column (currently called "Services", but that title is going away).
7. Change "Site Design: Feeling Responsive" to "Site Design: Feeling Responsive & Pygmeeweb"
8. Check that the same font and font size is being used in the footer everywhere - http://swctasks.github.io/workshop-template/index2.html and http://swcarpentry.github.io/website/ seem to be using different fonts (or different font sizes) for footer text.
9. Remove the text "License Blog GitHub Twitter Issues" currently in the footer for workshop-template/index2.html.

**Comment by djacquel** [comment]
Footer for workshop template or both sites ?

**Comment by gvwilson** [comment]
I think everywhere, non?

**Comment by djacquel** [comment]
OK

**Comment by djacquel** [comment]
1. ~~Use a three-column layout for the footer.~~
2. ~~Put the icons for GitHub, Twitter, and YouTube in the middle column.~~
3. Stack them vertically to save space (?).
4. Use this in all footers.
5. ~~Get rid of the titles "About This Site" and "Services".~~
6. ~~Add a link to 'License' to the right-hand column (currently called "Services", but that title is going away).~~
7. ~~Change "Site Design: Feeling Responsive" to "Site Design: Feeling Responsive & Pygmeeweb"~~

Pygmeeweb is not currently a marketing tool geared to Jekyll. Maybe latter. I'm thinking about a rework, I'll let You know.
But why not a page Credits listing Designer and open source technologies used
1. ~~Check that the same font and font size is being used in the footer everywhere - http://swctasks.github.io/workshop-template/index2.html and http://swcarpentry.github.io/website/ seem to be using different fonts (or different font sizes) for footer text.~~

Font in footer was to small = accessibility problem. It's now same size than the page font.
1. ~~Remove the text "License Blog GitHub Twitter Issues" currently in the footer for workshop-template/index2.html.~~

**Comment by gvwilson** [comment]
On 2015-12-09 5:27 PM, David Jacquel wrote:

> Pygmeeweb is not currently a marketing tool geared to Jekyll. Maybe 
> latter. I'm thinking about a rework, I'll let You know.
> But why not a page Credits listing Designer and open source 
> technologies used

+1 - in which case, we take the mention of Feeling Responsive out of the 
footer and instead have a link to "Credits" and put the details there.

> 1. Check that the same font and font size is being used in the footer
>    everywhere -
>    http://swctasks.github.io/workshop-template/index2.html and
>    http://swcarpentry.github.io/website/ seem to be using different
>    fonts (or different font sizes) for footer text.
> 
> Font in footer was to small = accessibility problem. It's now same 
> size than the page font.
> 
> thanks,
> Greg
