### ISSUE TITLE
Do we need both 'page' and 'page-fullwidth' layouts?

### ISSUE THREAD

**Issue by gvwilson** [swctasks/assets#3]
swcarpentry:website/pages/_.html uses only page-fullwidth as a layout, so all its pages are full-screen. datacarpentry:datacarpentry.github.io/pages/_.html uses only page as a layout, so all its pages are narrow. I propose that we:
1.  Replace 'page' with 'page-fullwidth' (so that there's only one layout for pages).
2.  Replace all uses of 'layout: page-fullwidth' with 'layout: page' in swcarpentry:website/pages/*.html

This will make all the Data Carpentry pages full width, and reduce the number of layouts we need to manage by one.

**Comment by swctasks** [comment]
I'll submit a PR in swcarpentry:website.
Can you open an issue there?

**Comment by gvwilson** [comment]
Please hold off until we hear back from @tracykteal on this one - she 
may want to keep the narrow layout for regular pages.
